name: Environment name sanitation from git branch name
description: Sanitize the environment name from the git branch name by removing all non alphanumeric characters and add a 'test-' prefix
outputs:
  environment_name:
    description: Environment name derivated from the git branch name and sanitized by removing all non alphanumeric characters with a 'test-' prefix
    value: "${{steps.sanitize_environment_name.outputs.env}}"

runs:
  using: composite
  steps:
    - id: sanitize_environment_name
      shell: python3 {0}
      env:
        GH_REF: ${{github.event.ref}}
      run: |
        import re
        import os

        # GITHUB_HEAD_REF is only set in a pull_request and contains the name of the branch.
        # ref: https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
        if os.environ.get('GITHUB_HEAD_REF') != "":
          branch_name=os.environ["GITHUB_HEAD_REF"]

        # GH_REF will contains the branch name that was pushed
        # in the format of 'refs/heads/<branch_name>'
        else:
          # strip the 'refs/heads/' from the branch name
          branch_name=os.environ["GH_REF"].replace("refs/heads/", "")

        # keep letters and numbers
        pattern = "[^0-9a-zA-Z\s]+"

        # perform a regex substitution to clean the branch name 
        # from any charachers except letters and numbers
        sanitized_branch_name = re.sub(pattern, "", branch_name).lower()

        print("##[set-output name=env;]test-"+sanitized_branch_name)